name: strawberry-openalea
channels:
 - openalea3
 - conda-forge
dependencies:
 - python
 - openalea.mtg 
 - openalea.plantgl 
 - oawidgets
 - openalea.strawberry
 - pip 
 - pandas 
 - k3d 
 - jupyter 
 - jupyterlab
 - voila 
 - voila-vuetify 
 - matplotlib
 - nodejs 
 - cufflinks-py 
 - ipyvuetify 
 - plotly
 - pyvis