name: hydroroot-openalea
channels:
  - openalea3
  - conda-forge
dependencies:
  - openalea.hydroroot
  - openalea.mtg
  - openalea.plantgl
  - openalea.lpy
  - jupyterlab>=3.0.16
  - matplotlib
  - numpy=1.20.*
  - pandas
  - pip
  - yaml
  - pyyaml
  - rsml