name: notebook-openalea
channels:
  - openalea3
  - conda-forge
  - fredboudon
dependencies:
  - openalea.mtg
  - openalea.plantgl
  - openalea.lpy
  - openalea.plantscan3d
  - jupyterlab>=3.0.16
  - jupyterlab_widgets
  - ipython=7
  - matplotlib
  - numpy=1.20.*
  - pandas
  - pip