name: openalea
channels:
  - openalea
  - conda-forge
dependencies:
  - python=2
  - scons
  - setuptools
  - openalea.deploy
  - openalea.sconsx
  - bison
  - flex
  - boost
  - ipython
  - jupyterlab
  - pip
